### ISSUE TITLE
Rebase to current clang master fails

### ISSUE THREAD

**Issue by erikzenker** [matus-chochlik/clang#14]
Is it planned to rebase the relfexpr branch onto the current clang master?

I tried it by myself, but there are a lot of conflicts and after fixing them it does not compile yet.

**Comment by matus-chochlik** [comment]
Hi, I know that the latest commit is terribly outdated, but for the moment I'm completely swamped at my day job. I hope that I'll have some free time in a couple of weeks.

**Comment by erikzenker** [comment]
I'll try to continue my rebase and fix the compile issues. Maybe I'll get it running.

**Comment by erikzenker** [comment]
I have opened a pull request with my rebase and compile issue fixes. Examples are not running yet. Link to the PR: https://github.com/matus-chochlik/clang/pull/15
