### ISSUE TITLE
get_base_name of reflected function pointer crashes

### ISSUE THREAD

**Issue by rbock** [matus-chochlik/clang#5]
The following code crashes clang:

```
#include <reflexpr>

constexpr auto foo() {}

int main()
{
  using X = reflexpr(foo);
  auto name = std::meta::get_base_name_v<X>;
}
```

Error messages attached:
[dump.txt](https://github.com/matus-chochlik/clang/files/679128/dump.txt)

**Comment by matus-chochlik** [comment]
Fixed by adding minimal support for function reflection.

**Comment by matus-chochlik** [comment]
Also disabled direct reflection of functions for now. The compiler prints proper diagnostic in such case.
