### ISSUE TITLE
meta_get_name_v crashes on scope of meta object

### ISSUE THREAD

**Issue by rbock** [matus-chochlik/clang#7]
Last issue for 2016 :-)

The following code crashes:

```C++
#include <iostream>
#include <reflexpr>

int main()
{
  using meta_int = reflexpr(int);
  using meta_meta_int = reflexpr(meta_int);
  using meta_meta_scope = std::meta::get_scope_m<meta_meta_int>;

  std::cout << std::meta::get_base_name_v<meta_meta_scope> << std::endl;
}
```

[attached error messages](https://github.com/matus-chochlik/clang/files/679715/log.txt)

If you move the type aliases into the global scope, it works fine.

Have a great New Year!

**Comment by matus-chochlik** [comment]
Thanks for all the feedback, seems I'll have a lot to do in 2017 ;)

A Great new year too!

**Comment by matus-chochlik** [comment]
Fixed by adding minimal support for function reflection. The scope of reflected local declarations is a meta-Function.
