### ISSUE TITLE
concept meta::DataMember still present

### ISSUE THREAD

**Issue by rbock** [matus-chochlik/clang#8]
The sixth revision dropped meta::DataMember. But this code

```C++
#include <reflexpr>
struct X
{
  static constexpr auto i = 0;
};

using bad = std::meta::get_elaborated_type_specifier_m<reflexpr(X::i)>;
```

lets the compiler say:

```
[...]
error: operation 'get_tag_specifier' not applicable to a 'meta-DataMember' metaobject
[...]
```

**Comment by matus-chochlik** [comment]
Replaced with "Operation 'X' not applicable to a metaobject reflecting a data member".
Internally the implementation keeps a much more detailed notion of metaobject concept than specified in the proposal, mostly for better diagnostics.
